version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./monitor:/home/airflow/monitor
            - ./files:/usr/local/airflow/files
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    db:
        image: mysql:5.7
        volumes:
            #- ./db_data:/var/lib/mysql
            - ./script/schema.sql:/docker-entrypoint-initdb.d/1.sql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test123

    web:
        build: streamlit-covid
        restart: always
        depends_on:
            - db	
        ports:
             - "8501:8501"
        volumes:
            - ./streamlit-covid/src:/app/src
